### ISSUE TITLE
minor adjustments

### ISSUE THREAD

**Issue by chrisbecker386** [chrisbecker386/Maintainer#128]
## Description
a few minor adjustments must be done.

## Implementation Plan

- [x] TaskCreation Spacing Card name and subtitle
- [x] All Creations Add button right sided
- [x] SettingsButton only on Overview Screen
- [x] all Buttons disabled on noPermission granded on SettingsScreen
