### ISSUE TITLE
add basic repository with an room db

### ISSUE THREAD

**Issue by chrisbecker386** [chrisbecker386/Maintainer#29]
## Feature Description

Add a repository.

## Acceptance Criteria
- [x] add a repository
- [x] preconditions (has task_id as fk)
- [x] tasks_completed_dates (has task_id as fk)
- [x] a task table
- [x] a step table(has task_id as fk)

## Suggested Solution
use [Room](https://developer.android.com/training/data-storage/room)

## Linked Issues
https://www.youtube.com/watch?v=bOd3wO0uFr8
