### ISSUE TITLE
add uiState to ViewModels

### ISSUE THREAD

**Issue by chrisbecker386** [chrisbecker386/Maintainer#40]
## Feature Description

the jetpack compose way of interaction is over a uiState, apply this to the existing ViewModels.

## Acceptance Criteria

- [x] add a ui-State to all viewModels
- [x] add the expected behave
- [x] it is only the TaskViewModel

## Suggested Solution
see the video, it explains how

## Linked Issues
[tutorial](https://www.youtube.com/watch?v=bOd3wO0uFr8)
