### ISSUE TITLE
enhance TaskCreation

### ISSUE THREAD

**Issue by chrisbecker386** [chrisbecker386/Maintainer#80]
## Feature Description
The Task Creation is not complete, Preconditions cannot not added, time interval is not editable and create steps is not possible.   

## Acceptance Criteria

- [ ] enhance creation logic with the params from the state class 
- [x] enhance ui 
- [x]  #77 
- [x]  #78 
- [x]  #79 
- [x] implemented a time picker so a time when the user should be reminded will defined
- [ ] the implemented #79 was reduced to TextInputField with a label so the composable is unnecessary and should be removed

## Suggested Solution

Include a brief description of the suggested solution for implementing the feature. You can also include links to relevant documentation or resources here.

## Linked Issues

Include links to any related issues or tasks that are necessary for completing this feature.
