### ISSUE TITLE
Remove useless tables and columns  

### ISSUE THREAD

**Issue by chrisbecker386** [chrisbecker386/Maintainer#92]
## Description
Remove unnecessary tables and columns. For example Preconditions (Table and ui) . They are impractical and not necessary for MVP.

## Implementation Plan
Remove the table, columns, the ui elements related to the entities and check the app behavior. It should be the same as before only without useless icons and infromation. 

## Goal
- [x] remove precondition table
- [x] remove precondition ui - element
- [x] remove step_image from steps table
- [x] update devData/testData
- [x] remove step image from ui - element for steps
- [x] remove task_duration from task table
- [x] remove task_duration ui - element for task ui elements
- [x] update ERD image in readme
- [x] same app behavior

## Time 
calculated: 3 hours
needed:
