### ISSUE TITLE
implement reminder notification

### ISSUE THREAD

**Issue by chrisbecker386** [chrisbecker386/Maintainer#93]
## Description
As a user I would like to reminded or to know which task I should do the comings days/weeks etc.

## Implementation Plan
Implement an Notification, that can be configured in the settings screen (how often a reminder should be fired and at what day and time)

## Goal
- [x] research how to support information
- [x] a permission should proper be requested
- [x] a woking notification
- [x] right information should be displayed
- [x] at the right time the notification should fired
- [x] link to the app should be offered the notification

## Time 
calculated: 8-16 hours
needed: 14 hours
