### ISSUE TITLE
add default tasks

### ISSUE THREAD

**Issue by chrisbecker386** [chrisbecker386/Maintainer#95]
## Description
Until now, only 2 real working task are made to use out of the box.
As a user I would like to have more than that

## Implementation Plan
Write more task for more sections and machines.

## Goal
- [x] add Sections (Garage, Utility room, Computer)
- [x] add Machines (Refrigerator, Washing Machine, Dryer, Dishwasher, Vacuum cleaner, car, bicycle)
- [x] min one task for each machine
- [x] Steps for each Task
